[package]
name = "webserv"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio ={ version = "1.0", features = ["full"]}
nom = "7.1.0"
tokio-util = "0.7.13"
anyhow = "1.0.94"
lazy_static = "1.5.0"
colored = "2.2.0"
